name: "$(SourceBranchName)+$(BuildID)"

# Prevents building every commit or on PR
trigger: none
pr: none

# Consume an artifact from the build pipeline as soon as it becomes available.
resources:
  pipelines:
    - pipeline: {{ config.meta.canonical_name }}
      source: "{{ config.meta.pipeline_name_prefix }}-Build"
      trigger:
        branches:
          exclude:
            - 'master'
            - "refs/heads/master"
            - 'refs/tags/v*'
  repositories:
    - repository: templates
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital

# env variables
variables:
  SERVICE_NAME: {{ config.meta.canonical_name }}
  SERVICE_BASE_PATH: {{ config.base_path }}
  PRODUCT_DISPLAY_NAME: {{ config.meta.name }}
  PRODUCT_DESCRIPTION: {{ config.meta.description }}
  AWS_ENV: ptl
  FORCE_SANDBOX: false
  NAMESPACE: from_branchname
  PROXY_NAME: live

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DeployInternalDev
    displayName: internal-dev
    variables:
    - group: apigee-nonprod
    - group: env-internal-dev
    jobs:
      - deployment: DeployService
        displayName: Deploy Service
        environment: 'internal-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: az/templates/pre-tasks.yml@templates
                - template: az/templates/setup-build-name.yml@templates
                - template: az/templates/deploy-namespaced-service.yml@templates
